- name: automatically select the OpenLDAP configuration settings
  shell: echo "slapd {{item}}" | sudo debconf-set-selections
  with_items:
         - slapd/password1 password {{ldap_server.admin_password}}
         - slapd/password2 password {{ldap_server.admin_password}}
         - slapd/allow_ldap_v2 boolean false
         - shared/organization string {{ldap_server.organization}}
         - slapd/no_configuration boolean false
         - slapd/move_old_database boolean true
         - slapd/purge_database boolean true
         - slapd/domain string {{ldap_server.domain}}
         - slapd/backend boolean HDB
