- name: automatically select the OpenLDAP configuration settings
  shell: echo "slapd {{item}}" | sudo debconf-set-selections
  with_items:
         - slapd/password1 password {{ldap_server.admin_password}}
         - slapd/password2 password {{ldap_server.admin_password}}
         - slapd/allow_ldap_v2 boolean false
         - shared/organization string {{ldap_server.organization}}
         - slapd/no_configuration boolean false
         - slapd/move_old_database boolean true
         - slapd/purge_database boolean true
         - slapd/domain string {{ldap_server.domain}}
         - slapd/backend boolean HDB

- name: install ldap apt packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - slapd
         - ldap-utils

- name: configure LDAP client tool
  template: src="ldap.conf"
            dest="/etc/ldap/ldap.conf"
            owner=root group=root mode=0644
  register: ldap_checkout

- name: generate sample LDAP directory
  template: src="ldap_content.ldif"
            dest="{{install_dir}}/ldap_content.ldif"

- name: load sample LDAP directory
  when: ldap_checkout.changed
  shell: chdir={{install_dir}}
         ldapadd
           -x -D cn=admin,{{ldap_server.base}}
           -w {{ldap_server.admin_password}}
           -f ldap_content.ldif