- name: automatically select the OpenLDAP configuration settings
  shell: echo "slapd {{item}}" | sudo debconf-set-selections
  with_items:
         - slapd/password1 password {{ldap_server_admin_password}}
         - slapd/password2 password {{ldap_server_admin_password}}
         - slapd/allow_ldap_v2 boolean false
         - shared/organization string {{ldap_server_organization}}
         - slapd/no_configuration boolean false
         - slapd/move_old_database boolean true
         - slapd/purge_database boolean true
         - slapd/domain string {{ldap_server_domain}}
         - slapd/backend boolean HDB

- name: install ldap apt packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - slapd
         - ldap-utils

- name: configure LDAP client tool
  template: src="ldap.conf.j2"
            dest="/etc/ldap/ldap.conf"
            owner=root group=root mode=0644
  register: ldap_checkout

- name: generate sample LDAP directory
  sudo_user: "{{username}}"
  template: src="ldap_content.ldif.j2"
            dest="{{install_dir}}/ldap_content.ldif"

- name: load sample LDAP directory
  when: ldap_checkout.changed
  shell: chdir={{install_dir}}
         ldapadd
           -x -D cn=admin,{{ldap_server_base}}
           -w {{ldap_server_admin_password}}
           -f ldap_content.ldif
  failed_when: False
           
- name: install certificate generator
  when: ldap_server_tls
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - gnutls-bin
         - ssl-cert

- name: configure certificate authority
  when: ldap_server_tls
  template: src="ca.info.j2"
            dest="/etc/ssl/ca.info"
         
- name: generate private key for certificate authority
  when: ldap_server_tls
  shell: sh -c "certtool --generate-privkey > /etc/ssl/private/cakey.pem"

            
- name: generate self-signed ca certificate
  when: ldap_server_tls
  shell: certtool --generate-self-signed
                  --load-privkey /etc/ssl/private/cakey.pem
                  --template /etc/ssl/ca.info
                  --outfile /etc/ssl/certs/cacert.pem

- name: configure ldap server certificate
  when: ldap_server_tls
  template: src="ldap01.info.j2"
            dest="/etc/ssl/ldap01.info"
            
- name: generate private key for ldap server
  when: ldap_server_tls
  shell: certtool --generate-privkey --bits 1024
                   --outfile /etc/ssl/private/ldap01_slapd_key.pem
            
- name: generate ldap server certificate
  when: ldap_server_tls
  shell: certtool --generate-certificate
                  --load-privkey /etc/ssl/private/ldap01_slapd_key.pem
                  --load-ca-certificate /etc/ssl/certs/cacert.pem
                  --load-ca-privkey /etc/ssl/private/cakey.pem
                  --template /etc/ssl/ldap01.info
                  --outfile /etc/ssl/certs/ldap01_slapd_cert.pem
                  
- name: configure ldap server certificate
  when: ldap_server_tls
  sudo_user: "{{username}}"
  template: src="certinfo.ldif.j2"
            dest="{{install_dir}}/certinfo.ldif"
            
- name: configure ldap server tls 
  when: ldap_server_tls
  shell: ldapmodify
           -Y EXTERNAL -H ldapi:///
           -f {{install_dir}}/certinfo.ldif
#  failed_when: False

- name: add openldap user to ssl-cert group
  user: name=openldap groups=ssl-cert

- name: set ldap private key permissions
  file: path=/etc/ssl/private/{{item}} group=ssl-cert mode=640
  with_items:
      - ldap01_slapd_key.pem
      - cakey.pem

- name: restart ldap server
  service: name=slapd state=restarted