- name: automatically select the OpenLDAP configuration settings
  tags: [ldap]
  shell: echo "slapd {{item}}" | sudo debconf-set-selections
  with_items:
         - slapd/password1 password {{ldap_server_admin_password}}
         - slapd/password2 password {{ldap_server_admin_password}}
         - slapd/allow_ldap_v2 boolean false
         - shared/organization string {{ldap_server_organization}}
         - slapd/no_configuration boolean false
         - slapd/move_old_database boolean true
         - slapd/purge_database boolean true
         - slapd/domain string {{ldap_server_domain}}
         - slapd/backend boolean HDB

- name: install ldap apt packages
  tags: [ldap]
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - slapd
         - ldap-utils

- name: configure LDAP client tool
  tags: [ldap]
  template: src="ldap.conf.j2"
            dest="/etc/ldap/ldap.conf"
            owner=root group=root mode=0644
  register: ldap_checkout

- name: generate sample LDAP directory
  tags: [ldap]
  sudo_user: "{{username}}"
  template: src="ldap_content.ldif.j2"
            dest="{{install_dir}}/ldap_content.ldif"

- name: load sample LDAP directory
  tags: [ldap]
  when: ldap_checkout.changed
  shell: chdir={{install_dir}}
         ldapadd
           -x -D cn=admin,{{ldap_server_base}}
           -w {{ldap_server_admin_password}}
           -f ldap_content.ldif
  failed_when: False
           
- name: install certificate generator
  tags: [ldap]
  when: ldap_server_tls and not use_custom_ssl_certificates
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - gnutls-bin
         - ssl-cert
         
- name: create ldap ssl certificates directory
  tags: [ldap]
  when: ldap_server_tls
  file: path=/etc/ldap/ssl state=directory owner=root group=ssl-cert mode=0640

- name: configure certificate authority
  tags: [ldap]
  when: ldap_server_tls and not use_custom_ssl_certificates
  template: src="ldap_ca.info.j2"
            dest="/etc/ldap/ssl/ldap_ca.info"
         
- name: generate private key for certificate authority
  tags: [ldap]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: sh -c "certtool --generate-privkey > /etc/ldap/ssl/ldap_cakey.pem"

            
- name: generate self-signed ca certificate
  tags: [ldap]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: certtool --generate-self-signed
                  --load-privkey /etc/ldap/ssl/ldap_cakey.pem
                  --template /etc/ldap/ssl/ldap_ca.info
                  --outfile /etc/ldap/ssl/ldap_cacert.pem

- name: configure ldap server certificate
  tags: [ldap]
  when: ldap_server_tls and not use_custom_ssl_certificates
  template: src="ldap01.info.j2"
            dest="/etc/ldap/ssl/ldap01.info"
            
- name: generate private key for ldap server
  tags: [ldap]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: certtool --generate-privkey --bits 1024
                   --outfile /etc/ldap/ssl/ldap01_slapd_key.pem
            
- name: generate ldap server certificate
  tags: [ldap]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: certtool --generate-certificate
                  --load-privkey /etc/ldap/ssl/ldap01_slapd_key.pem
                  --load-ca-certificate /etc/ldap/ssl/ldap_cacert.pem
                  --load-ca-privkey /etc/ldap/ssl/ldap_cakey.pem
                  --template /etc/ldap/ssl/ldap01.info
                  --outfile /etc/ldap/ssl/ldap01_slapd_cert.pem
                  
- name: copy custom ldap ssl certificates
  tags: [ldap]
  when: ldap_server_tls and use_custom_ssl_certificates
  copy: src={{custom_ssl_certificates_path|default('certificates')}}/ldap/
        dest=/etc/ldap/ssl

- name: configure ldap server tls 
  tags: [ldap]
  when: ldap_server_tls
  shell: ldapmodify
           -Y EXTERNAL -H ldapi:///
           -f /vagrant/provisioning/roles/common/files/ldap_tls_config.ldif
#  failed_when: False

- name: disable ldap server tls 
  tags: [ldap]
  when: not ldap_server_tls
  shell: ldapmodify
           -Y EXTERNAL -H ldapi:///
           -f /vagrant/provisioning/roles/common/files/ldap_disable_auth.ldif

- name: add openldap user to ssl-cert group
  tags: [ldap]
  user: name=openldap groups=ssl-cert

- name: set ldap private key permissions
  tags: [ldap]
  file: path=/etc/ldap/ssl/{{item}} group=ssl-cert mode=640
  with_items:
      - ldap01_slapd_key.pem
      - ldap_cakey.pem

- name: restart ldap server
  tags: [ldap]
  service: name=slapd state=restarted
  
- name: clear truststore
  tags: [ldap]
  file: name={{install_dir}}/keystore state=absent
  
- name: import ca certificate in truststore
  tags: [ldap]
  sudo_user: "{{username}}"
  when: ldap_server_tls
  shell: /bin/echo -e "{{keystore_password}}\n{{keystore_password}}\nyes\n" | keytool
           -importcert -trustcacerts
           -file /etc/ldap/ssl/ldap_cacert.pem
           -keystore {{install_dir}}/keystore
  failed_when: False
  