- name: add PPA repos
  apt_repository: repo={{item}}
  with_items: ['ppa:webupd8team/java','ppa:nginx/stable']

- name: update apt cache 
  apt: update_cache=yes
  
- name: upgrade server packages
  apt: upgrade=full

- name: automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install Oracle Java
  apt: pkg=oracle-java7-installer

- name: set global JAVA_HOME
  lineinfile: dest=/etc/environment
              state=present
              regexp='^JAVA_HOME'
              line='JAVA_HOME={{java_home_dir}}'

- name: download jetty-runner
  tags: [apps]
  get_url: 
          url={{jetty.download_url}}
          dest={{install_dir}}/jetty-runner.jar
 
- include: ldap.yml
- include: smart-on-fhir.yml
- include: oidc.yml
- include: sample-data.yml



