- name: create group
  group: name="{{username}}"
  
- name: create user
  user: name="{{username}}" password="{{userpass}}"
        group="{{username}}" groups=sudo
        shell=/bin/bash

- name: add PPA repos
  apt_repository: repo={{item}}
  with_items: ['ppa:webupd8team/java','ppa:nginx/stable']

- name: update aptitude cache 
  apt: update_cache=yes
  
- name: upgrade server packages
  apt: upgrade=full
  
- name: install prerequisite packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - git
         - nginx
         - maven
         - postgresql
         - python-psycopg2
         - python-jinja2

- name: automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install Oracle Java
  apt: pkg=oracle-java7-installer

- name: set global JAVA_HOME
  lineinfile: dest=/etc/environment
              state=present
              regexp='^JAVA_HOME'
              line='JAVA_HOME={{java_home_dir}}'

- name: download jetty-runner
  tags: [apps]
  sudo_user: "{{username}}"
  get_url: 
          url={{jetty.download_url}}
          dest={{install_dir}}/jetty-runner.jar

- name: create ssl certificates directory
  file: path=/etc/nginx/ssl state=directory owner=root group=root mode=0640

# TO DO: templetize certificate settings and generate individual certificates for each server
- name: generate self-signed ssl certificates
  shell: cat /vagrant/certificate_settings.txt | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt
 
- include: ldap.yml
- include: smart-on-fhir.yml
- include: auth-server.yml
- include: sample-data.yml