- name: checkout OpenID Connect server
  tags: [oidc]
  git: repo={{auth_server.repo}}
       version={{auth_server.branch}}
       dest={{install_dir}}/ldap-openid-connect-server

- name: build OpenID Connect server
  tags: [oidc]
  environment:
    JAVA_HOME: "{{java_home_dir}}"
  shell: chdir={{install_dir}}/ldap-openid-connect-server
       mvn package -DskipTests=true -Dmaven.javadoc.skip=true

- name: configure OpenID Connect server service
  tags: [oidc]
  template: src=oidc.conf.j2
            dest=/etc/init/oidc.conf
            owner=root group=root mode=0644

- name: restart OpenID Connect server
  tags: [oidc]
  service: name=oidc state=restarted

- name: wait for auth server to become available
  tags: [oidc]
  wait_for: port=4000 delay=10
          
- name: configure nginx (OpenID Connect server)
  tags: [oidc]
  template: src=nginx_oidc.j2 dest=/etc/nginx/sites-enabled/oidc owner=root group=root mode=0644
  notify:
        - restart nginx

- meta: flush_handlers


