- name: checkout sample patients
  sudo_user: "{{username}}"
  git: repo={{sample_patients_repo}}
       version={{sample_patients_branch}}
       dest={{install_dir}}/smart_sample_patients
  register: sample_patients_checkout

- name: build sample patients
  sudo_user: "{{username}}"
  when: sample_patients_checkout.changed
  shell: chdir={{install_dir}}/smart_sample_patients/bin
         python generate.py --write-fhir ../generated-data

- name: list 10 sample patients
  tags: [pts]
  shell: ls {{install_dir}}/smart_sample_patients/generated-data/*.xml | head -n 10
  register: sample_patient_files

- name: load sample patients
  tags: [pts]
  when: sof_checkout.changed or sample_patients_checkout.changed
  shell: "chdir={{install_dir}}/smart_sample_patients/generated-data/
         curl
           -u {{fhir_server_username}}:{{fhir_server_password}}
           'http://localhost:3000/?'
           -H 'Content-Type: text/xml' 
           --data-binary @{{item}}"
  with_items: sample_patient_files.stdout_lines

- name: checkout fhir-starter apps
  tags: [apps,load_apps]
  sudo_user: "{{username}}"
  git: repo={{app_server_repo}}
       version={{app_server_branch}}
       dest={{install_dir}}/fhir-starter
  register: apps_checkout

- name: configure fhir-starter
  tags: [apps,load_apps]
  sudo_user: "{{username}}"
  shell: sed -i -e 's/http:\/\/localhost:9080/{{ fhir_server_base | regex_replace('/', '\\/') }}/' {{install_dir}}/fhir-starter/static/fhirStarter/services.js

- name: list sample apps
  tags: [apps, load_apps]
  shell: cat {{install_dir}}/fhir-starter/static/fhirStarter/apps.json
  register: sample_apps

- name: load sample apps
  tags: [apps, load_apps]
  when: sof_checkout.changed or apps_checkout.changed or auth_checkout.changed or auth_service.changed
  uri: 
     url='{{auth_server_base}}/api/clients'
     method=POST
     user={{auth_server_username}}
     password={{auth_server_password}}
     HEADER_Content-Type="application/json"
     status_code=200
     force_basic_auth=yes
     body='{{ lookup('template', '../templates/load_app.j2') }}'
  # Note: this generates a warning with Ansible 1.6.1, but actually is correct
  with_items: "{{ sample_apps.stdout | to_json }}"
