- name: checkout sample patients
  git: repo={{sample_patients.repo}}
       version={{sample_patients.branch}}
       dest={{install_dir}}/smart_sample_patients
  register: sample_patients_checkout

- name: build sample patients
  when: sample_patients_checkout.changed
  shell: chdir={{install_dir}}/smart_sample_patients/bin
         python generate.py --write-fhir ../generated-data

- name: list 10 sample patients
  tags: [pts]
  shell: ls {{install_dir}}/smart_sample_patients/generated-data/*.xml | head -n 10
  register: sample_patient_files

- name: load sample patients
  tags: [pts]
  when: sof_checkout.changed or sample_patients_checkout.changed
  shell: "chdir={{install_dir}}/smart_sample_patients/generated-data/
         curl
           -u {{fhir_server.admin.username}}:{{fhir_server.admin.password}}
           'http://localhost:3000/?'
           -H 'Content-Type: text/xml' 
           --data-binary @{{item}}"
  with_items: sample_patient_files.stdout_lines

- name: checkout fhir-starter apps
  tags: [apps,load_apps]
  git: repo={{app_server.repo}}
       version={{app_server.branch}}
       dest={{install_dir}}/fhir-starter
  register: apps_checkout

- name: list sample apps
  tags: [apps, load_apps]
  shell: cat {{install_dir}}/fhir-starter/static/fhirStarter/apps.json
  register: sample_apps

- name: load sample apps
  tags: [apps, load_apps]
  when: sof_checkout.changed or apps_checkout.changed
  uri: 
     url='http://localhost:4000/api/clients'
     method=POST
     user={{auth_server.admin.username}}
     password={{auth_server.admin.password}}
     HEADER_Content-Type="application/json"
     status_code=200
     force_basic_auth=yes
     body='{{ lookup('template', '../templates/load_app.j2') }}'
  # Note: this generates a warning with Ansible 1.6.1, but actually is correct
  with_items: "{{sample_apps.stdout | to_json}}"
