- name: checkout sample patients
  sudo_user: "{{username}}"
  git: repo={{sample_patients_repo}}
       version={{sample_patients_branch}}
       dest={{install_dir}}/smart_sample_patients
  register: sample_patients_checkout

- name: build sample patients
  sudo_user: "{{username}}"
  shell: chdir={{install_dir}}/smart_sample_patients/bin
         python generate.py --write-fhir ../generated-data

- name: list 10 sample patients
  tags: [pts]
  shell: ls {{install_dir}}/smart_sample_patients/generated-data/*.xml | head -n 10
  register: sample_patient_files

- name: load sample patients
  tags: [pts]
  when: 
    sof_checkout.changed or sample_patients_checkout.changed
    and (not fhir_server_preserve_db)
  shell: "chdir={{install_dir}}/smart_sample_patients/generated-data/
         curl
           -u {{fhir_server_username}}:{{fhir_server_password}}
           'http://localhost:3000/?'
           -H 'Content-Type: text/xml' 
           --data-binary @{{item}}"
  with_items: sample_patient_files.stdout_lines

- name: checkout fhir-starter apps
  tags: [apps]
  sudo_user: "{{username}}"
  git: repo={{app_server_repo}}
       version={{app_server_branch}}
       dest={{install_dir}}/fhir-starter
  register: apps_checkout

- name: configure fhir-starter
  tags: [apps]
  sudo_user: "{{username}}"
  shell: sed -i -e 's/http:\/\/localhost:9080/{{ fhir_server_base | regex_replace('/', '\\/') }}/' {{install_dir}}/fhir-starter/static/fhirStarter/services.js

- name: list sample apps
  tags: [apps, load_apps]
  shell: cat {{install_dir}}/fhir-starter/static/fhirStarter/apps.json
  register: sample_apps

- name: copy load-app script
  tags: [apps, load_apps]
  copy: src=load_sample_app.py dest={{install_dir}} mode=700
 
- name: load sample app
  tags: [apps, load_apps]
  shell: chdir={{install_dir}}
     ./load_sample_app.py
         '{{lookup('template', '../templates/load_app.j2')}}'
         '{{auth_server_base}}'
         '{{auth_server_username}}'
         '{{auth_server_password}}'
  with_flattened: 
    - "{{ sample_apps.stdout | to_json }}"
