- name: install apt packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - git
         - nginx
         - slapd
         - ldap-utils
         - maven
         - postgresql
         - python-psycopg2
         - python-jinja2
         
- name: configure smart-on-fhir service
  template: src=smart-on-fhir.conf.j2
            dest=/etc/init/smart-on-fhir.conf
            owner=root group=root mode=0644

- name: stop smart-on-fhir
  service: name=smart-on-fhir state=stopped

- name: configure postgres
  copy: src=pg_hba.conf
        dest=/etc/postgresql/9.3/main/pg_hba.conf

- name: restart postgres
  service: name=postgresql state=restarted

- name: create postgres user
  sudo_user: postgres
  postgresql_user: 
          name={{postgres.user}} 
          password={{postgres.password}}
          role_attr_flags=SUPERUSER

- name: checkout smart-on-fhir
  git: repo={{fhir_server.repo}}
       version={{fhir_server.branch}}
       dest={{install_dir}}/smart-on-fhir

- name: build smart-on-fhir server
  environment:
    JAVA_HOME: "{{java_home_dir}}"
  shell: chdir={{install_dir}}/smart-on-fhir
        ./grailsw dev war

- name: drop postgres db
  sudo_user: postgres
  postgresql_db: state=absent name=fhir
          
- name: create postgres db
  sudo_user: postgres
  postgresql_db: name=fhir owner={{postgres.user}}

- name: install smart-on-fhir tables
  environment:
    JAVA_HOME: "{{java_home_dir}}"
  shell: chdir={{install_dir}}/smart-on-fhir
        ./grailsw -DnoTomcat=true run-script scripts/CreateDatabase.groovy

- name: restart smart-on-fhir
  service: name=smart-on-fhir state=restarted
 
- name: wait for smart-on-fhir server to become available
  wait_for: port=3000 delay=10

- name: checkout sample patients
  tags: [pts]
  git: repo={{sample_patients.repo}}
       version={{sample_patients.branch}}
       dest={{install_dir}}/smart_sample_patients

- name: build sample patients
  tags: [pts]
  shell: chdir={{install_dir}}/smart_sample_patients/bin
         python generate.py --write-fhir ../generated-data

- name: copy load pt script
  tags: [pts]
  copy: src=load-patients.sh 
        dest={{install_dir}}/smart_sample_patients/generated-data/

- name: make load pt script executable
  tags: [pts]
  acl: name={{install_dir}}/smart_sample_patients/generated-data/load-patients.sh
       permissions=rx
       etype=user
       state=present

- name: load sample patients
  tags: [pts]
  shell: chdir={{install_dir}}/smart_sample_patients/generated-data
         ./load-patients.sh

- name: checkout fhir-starter apps
  tags: [apps]
  git: repo={{app_server.repo}}
       version={{app_server.branch}}
       dest={{install_dir}}/fhir-starter

- name: install sample apps
  tags: [apps]
  uri: url={{auth_server.public.pretty}}/api/clients
       method=POST
       user={{auth_server.admin.username}}
       password={{auth_server.admin.password}}
       body="{{ lookup('file', '../templates/load_app.j2' )}}" force_basic_auth=yes status_code=201 HEADER_Content-Type="application/json"

