---
- hosts: all
  sudo: true
  vars:
    use_custom_ssl_certificates: true
    custom_ssl_certificates_path: ../../private/fhir_ci_certs
    auth_server_secure_http: true
    auth_server_host: "ci-auth.fhir.me"
    auth_server_port: "443"
    fhir_server_secure_http: true
    fhir_server_host: "ci-api.fhir.me"
    fhir_server_port: "443"
    app_server_secure_http: true
    app_server_host: "ci.fhir.me"
    app_server_port: "443"
  roles:
    - common
