---
keystore_password: "changeme"
username: "fhir"
userpass: "secretpass"
auth_server_host: "localhost"
fhir_server_host: "localhost"
app_server_host: "localhost"
docs_server_host: "localhost"
#use_custom_ssl_certificates: false
#custom_ssl_certificates_path: /example/local/path
#fhir_server_branch: "master"
#auth_ldap_server_branch: "smart-launch"
#sample_patients_branch: "master"
#auth_server_branch: "smart-launch"
#fhir_starter_branch: "master"
#cardiac_risk_branch: "master"
#bp_centiles_branch: "master"
#growth_chart_branch: "master"
#fhir_demo_app_branch: "master"