---
keystore_password: "changeme"
username: fhir
userpass: secretpass
auth_server_host: localhost
fhir_server_host: localhost
app_server_host: localhost
docs_server_host: localhost
#use_custom_ssl_certificates: false
#custom_ssl_certificates_path: /example/local/path
fhir_server_branch: v0.0.5
auth_server_branch: f0.0.5
auth_ldap_server_branch: f0.0.4
sample_patients_branch: v0.0.5
fhir_starter_branch: v0.0.5
cardiac_risk_branch: v0.0.5
bp_centiles_branch: v0.0.5
growth_chart_branch: v0.0.5
fhir_demo_app_branch: v0.0.5
mpr_monitor_branch: v0.0.5
diabetes_monograph_branch: v0.0.5
disease_monograph_branch: v0.0.5
