---
- hosts: all
  sudo: true
  vars:
    keystore_password: "SECRET1"
    userpass: "SECRET2"
    auth_server_password: "SECRET3"
    fhir_server_password: "SECRET4"
    ldap_server_admin_password: "SECRET5"
    docs_webhook_secret: "SECRET6"
    username: "fhir"
    auth_server_host: "authorize-dstu2.smarthealthit.org"
    fhir_server_host: "fhir-api-dstu2.smarthealthit.org"
    app_server_host: "fhir-dstu2.smarthealthit.org"
    fhir_server_secure_http: true
    app_server_secure_http: true
    auth_server_secure_http: true
    fhir_server_port: 443
    app_server_port: 443
    auth_server_port: 443
    sample_patients_limit: 9999
    ldap_server_domain: "smarthealthit.org"
    ldap_server_host: "ldap-dstu2.smarthealthit.org"
    ldap_server_base: "dc=smarthealthit,dc=org"
    ldap_server_uri: "ldap://{{ldap_server_host}}:389"
    ldap_server_organization: "SMART Health IT"
    ldap_server_tls: false
    use_custom_ssl_certificates: true
    custom_ssl_certificates_path: ../../certificates
    fhir_server_branch: "dstu2-wip"
    app_server_branch: "sandbox-dstu2"
    sample_patients_branch: "dstu2-wip"
    auth_ldap_server_branch: "sandbox"
    auth_server_branch: "sandbox"
    force_rebuild: true
  roles:
    - common
