---
install_dir: "/opt"
java_home_dir: "/usr/lib/jvm/java-7-oracle"
jetty:
  download_url: "http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.1.0.M0/jetty-runner-9.1.0.M0.jar"
postgres:
  user: "fhir"
  password: "fhir"
auth_server:
  admin:
    username: client
    password: secret
  public:
    port: 9085
    host: "localhost"
    base: "http://localhost:9085"
  repo: "https://github.com/jmandel/OpenID-Connect-Java-Spring-Server.git"
  branch: "smart-launch"
  war: ldap-openid-connect-server/openid-connect-server-webapp/target/openid-connect-server-webapp.war
fhir_server: 
  public:
    port: 9080
    host: "localhost"
    base: "http://localhost:9080"
  admin:
    username: client
    password: secret
  use_auth: true
  repo: "https://github.com/smart-on-fhir/smart-on-fhir.git"
  branch: "smart-launch"
  introspection_uri: "{{auth_server.public.base}}/introspect?token={token}"
  register_uri: "{{auth_server.public.base}}/register"
  authorize_uri: "{{auth_server.public.base}}/authorize"
  token_uri: "{{auth_server.public.base}}/token"
app_server: 
  public:
    port: 9090
    host: "localhost"
    base: "http://localhost:9090"
  repo: "https://github.com/smart-on-fhir/fhir-starter.git"
  branch: "smart-launch"

ldap_server:
  domain: "example.com"
  base: "dc=example,dc=com"
  uri: "ldap://localhost:389"
  organization: "Example Company"
  admin_password: "sample-password"

sample_patients:
  repo: "https://github.com/chb/smart_sample_patients.git"
  branch: "fhir"