---
postgres:
  user: "fhir"
  password: "fhir"
fhir_server: 
  base_url: "http://localhost:9080"
  use_auth: false
ldap_server:
  domain: "smartplatforms.org"
  organization: "SMART Platforms"
  admin_password: "4p923epslKq3"
