---
install_dir: "/opt"
java_home_dir: "/usr/lib/jvm/java-7-oracle"
jetty:
  download_url: "http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.1.0.M0/jetty-runner-9.1.0.M0.jar"
postgres:
  user: "fhir"
  password: "fhir"
auth_server:
  base_url: "http://localhost:9085"
  repo: "https://github.com/nschwertner/ldap-openid-connect-server.git"
  branch: "master"
fhir_server: 
  base_url: "http://localhost:9080"
  use_auth: false
  repo: "https://github.com/nschwertner/smart-on-fhir.git"
  branch: "master"
  introspection_uri: "{{auth_server.base_url}}/introspect?token={token}"
  register_uri: "{{auth_server.base_url}}/register"
  authorize_uri: "{{auth_server.base_url}}/authorize"
  token_uri: "{{auth_server.base_url}}/token"
ldap_server:
  domain: "example.com"
  base: "dc=example,dc=com"
  uri: "ldap://localhost:389"
  organization: "Example Company"
  admin_password: "sample-password"
sample_patients:
  repo: "https://github.com/chb/smart_sample_patients.git"
  branch: "fhir"